# Generated by Django 3.0.7 on 2020-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('log1', models.ImageField(upload_to='pics')),
                ('team1', models.CharField(max_length=30)),
                ('log2', models.ImageField(upload_to='pics')),
                ('team2', models.CharField(max_length=30)),
                ('ground', models.CharField(max_length=700)),
                ('winner', models.CharField(max_length=700)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
